"""Mock OpenAI + Anthropic + Gemini provider for e2e testing — zero provider cost.

Started by the e2e/_config/docker-compose.yml `mock` service when the
`mock` profile is active (`e2e/tools/proxy start --with-mock`). Stdlib-only,
no install step.

Endpoints
---------
  POST /v1/chat/completions                                OpenAI-shape, stream + non-stream
  POST /v1/messages                                         Anthropic-shape, stream + non-stream
  POST /v1beta/models/<model>:generateContent              Gemini non-stream
  POST /v1beta/models/<model>:streamGenerateContent        Gemini stream (SSE)
  POST /api/public/ingestion                                Langfuse-style ingestion sink
  POST /api/hooks/*                                         GenericAPILogger / generic webhook sink
  POST /api/v1/series                                       Datadog-style metrics sink (drop)
  GET  /healthz                                             health probe (always 200)
  GET  /api/public/projects                                 stub for langfuse SDK init probe
  GET  /__mock__/state                                      snapshot all internal counters as JSON
  GET  /__mock__/reset                                      reset counters (returns 204)
  GET  /metrics                                             Prometheus text-format scrape

Process-level env (compose-managed, all defaults are "fast & deterministic")
---------------------------------------------------------------------------
  MOCK_TTFT_MS       int     delay (ms) before first chunk; default 0
  MOCK_TPS           int     chunks emitted per second (streaming); default 100
  MOCK_CHUNKS        int     total chunks per streamed response; default 100
  CALLBACK_DELAY     float   seconds the callback sinks sleep before responding; default 0
  FAIL_RATE          float   0..1 fraction of provider calls returning 503; default 0

Per-request overrides — preferred path (HTTP headers, survives transforms)
----------------------------------------------------------------------------
  X-Mock-Chunks        int     overrides MOCK_CHUNKS for this call
  X-Mock-Chunk-Chars   int     chars per chunk; default 40
  X-Mock-Full-Chars    int     total chars for non-streaming reply; default 8000
  X-Mock-TTFT-Ms       int     overrides MOCK_TTFT_MS for this call
  X-Mock-TPS           int     overrides MOCK_TPS for this call
  X-Mock-Fail          str     "503"|"429"|"401"|"400"|"500" — force this call to error
  X-Mock-Tool-Call     str     `name(k1=v1,k2=v2)` — emit a tool-call instead
                               of a normal text response. Works on all three
                               provider paths; format adapts (tool_calls /
                               tool_use / functionCall). String args only.
                               Examples:
                                 get_weather(city=Tokyo,unit=celsius)
                                 ping()

Per-request overrides — legacy fallback (JSON body fields)
----------------------------------------------------------
Same fields with `mock_` prefix (mock_chunks, mock_ttft_ms, ...). These
only work for OpenAI chat completion routing — Anthropic and Gemini
transforms strip unknown body fields, so the **headers above are
required** for those provider paths. The rendered litellm config
generated by `e2e/tools/proxy start --with-mock` opts into
`general_settings.forward_client_headers_to_llm_api: true` so X-Mock-*
headers reach the mock automatically.

Usage examples
--------------
  # Slow streaming (matches a production TTFT=15s, TPS=30 profile):
  MOCK_TTFT_MS=15000 MOCK_TPS=30 MOCK_CHUNKS=1500 \\
    e2e/tools/proxy start --with-mock

  # Retry-amplification: 30% of provider calls return 503:
  MOCK_FAIL_RATE=0.3 e2e/tools/proxy start --with-mock

  # Slow async-callback consumer (Langfuse / generic webhook stuck):
  MOCK_CALLBACK_DELAY=8 e2e/tools/proxy start --with-mock

The companion auto-rendered config (e2e/_config/.litellm.rendered.yaml,
generated by `e2e/tools/proxy`) adds three model_list entries when --with-mock
is passed:
  - mock-openai     -> openai/mock-model        api_base: http://mock:8080/v1
  - mock-anthropic  -> anthropic/mock-claude    api_base: http://mock:8080
  - mock-gemini     -> gemini/mock-gemini-pro   api_base: http://mock:8080/v1beta
"""

from __future__ import annotations

import json
import os
import sys
import time
import string
import random
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Optional

PORT = 8080
ALPHABET = string.ascii_letters + string.digits + " "

# Pool of random text built ONCE at import. The pool itself is immutable
# after construction so reading slices from it is thread-safe.
_POOL = "".join(random.Random(0).choice(ALPHABET) for _ in range(1_000_000))

# Thread-local RNG — each worker thread gets its own independent
# random.Random instance, eliminating the lock contention + nondeterministic
# interleaving of a module-level `_RNG.randint()` across handler threads
# under ThreadingHTTPServer.
_tls = threading.local()


def _rng() -> random.Random:
    rng = getattr(_tls, "rng", None)
    if rng is None:
        # Seed off thread id so failures are reproducible per-thread but
        # threads don't draw identical sequences.
        rng = random.Random(threading.get_ident())
        _tls.rng = rng
    return rng


# Defaults from env (overridable per-request via JSON body).
DEFAULT_TTFT_MS = int(os.environ.get("MOCK_TTFT_MS", "0"))
DEFAULT_TPS = int(os.environ.get("MOCK_TPS", "100"))
DEFAULT_CHUNKS = int(os.environ.get("MOCK_CHUNKS", "100"))


# -----------------------------------------------------------------------------
# Counters for /__mock__/state introspection + /metrics Prometheus scrape.
# -----------------------------------------------------------------------------
class Stats:
    """Process-wide atomic counters shared across handler threads.

    A single threading.Lock guards every increment. Reads return a shallow
    copy so callers can iterate without holding the lock.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        # bumped per HTTP request, keyed by (provider, mode, status)
        # provider ∈ {"openai","anthropic","gemini","callback","other"}
        # mode     ∈ {"stream","unary","sink","probe"}
        # status   ∈ HTTP status code (int)
        self.requests: dict[tuple[str, str, int], int] = {}
        # bumped per emitted SSE chunk, keyed by provider
        self.chunks: dict[str, int] = {}
        # bumped per forced/random-injected failure, keyed by HTTP status
        self.errors_injected: dict[int, int] = {}
        # in-flight count, monotonically increases on enter, decreases on exit
        self.in_flight = 0
        # started_at for uptime
        self.started_at = time.time()

    def request(self, provider: str, mode: str, status: int) -> None:
        with self._lock:
            self.requests[(provider, mode, status)] = (
                self.requests.get((provider, mode, status), 0) + 1
            )

    def chunk(self, provider: str, n: int = 1) -> None:
        with self._lock:
            self.chunks[provider] = self.chunks.get(provider, 0) + n

    def fail(self, status: int) -> None:
        with self._lock:
            self.errors_injected[status] = self.errors_injected.get(status, 0) + 1

    def enter(self) -> None:
        with self._lock:
            self.in_flight += 1

    def exit(self) -> None:
        with self._lock:
            self.in_flight = max(0, self.in_flight - 1)

    def snapshot(self) -> dict:
        with self._lock:
            return {
                "uptime_s": round(time.time() - self.started_at, 2),
                "in_flight": self.in_flight,
                "requests": {
                    f"{p}:{m}:{s}": n for (p, m, s), n in self.requests.items()
                },
                "chunks": dict(self.chunks),
                "errors_injected": dict(self.errors_injected),
            }


STATS = Stats()


def chunk_text(size: int) -> str:
    rng = _rng()
    if size <= len(_POOL):
        start = rng.randint(0, len(_POOL) - size)
        return _POOL[start : start + size]
    return (_POOL * ((size // len(_POOL)) + 1))[:size]


def compact_json(obj) -> bytes:
    """Emit JSON the way real providers do — no whitespace between separators.

    Critical for SSE chunks: existing client/test code (and litellm itself)
    sometimes does regex / awk matching against the raw `data: {...}` line
    expecting tight `"key":"value"` form. Default `json.dumps` inserts
    `", "` and `": "` which silently breaks those matchers.
    """
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":")).encode("utf-8")


def anthropic_event(event_type: str, data: dict) -> bytes:
    return (
        f"event: {event_type}\n".encode("utf-8")
        + b"data: "
        + compact_json(data)
        + b"\n\n"
    )


def sse_chunk_openai(
    model: str, idx: int, delta_text: str, finish: bool = False
) -> bytes:
    obj = {
        "id": f"chatcmpl-mock-{idx}",
        "object": "chat.completion.chunk",
        "created": int(time.time()),
        "model": model,
        "choices": [
            {
                "index": 0,
                "delta": {} if finish else {"content": delta_text},
                "finish_reason": "stop" if finish else None,
            }
        ],
    }
    return b"data: " + compact_json(obj) + b"\n\n"


def gemini_chunk(
    delta_text: str,
    *,
    finish: bool = False,
    prompt_tokens: int = 0,
    output_tokens: int = 0,
) -> bytes:
    """Encode one Gemini SSE chunk.

    Gemini stream wire format is JSON objects separated by `\\n\\r\\n` with
    each chunk a complete GenerateContentResponse. The final chunk carries
    `finishReason="STOP"` and a `usageMetadata` block.
    """
    obj: dict = {
        "candidates": [
            {
                "content": {"parts": [{"text": delta_text}], "role": "model"},
                "index": 0,
            }
        ],
    }
    if finish:
        obj["candidates"][0]["finishReason"] = "STOP"
        obj["usageMetadata"] = {
            "promptTokenCount": prompt_tokens,
            "candidatesTokenCount": output_tokens,
            "totalTokenCount": prompt_tokens + output_tokens,
        }
    return b"data: " + compact_json(obj) + b"\r\n\r\n"


def parse_gemini_path(path: str) -> tuple[str, bool]:
    """Parse `/v1beta/models/<model>:<action>` → (model, is_stream).

    Tolerates `?alt=sse&key=...` query params and missing `/v1beta` prefix.
    """
    base = path.split("?", 1)[0]
    is_stream = ":streamGenerateContent" in base
    # extract model between `/models/` and `:` (works for both action verbs)
    if "/models/" in base and ":" in base.split("/models/", 1)[1]:
        model = base.split("/models/", 1)[1].split(":", 1)[0]
    else:
        model = "mock-gemini"
    return model, is_stream


def paced_iter(start_monotonic: float, interval: float, count: int):
    """Yield i for i in range(count), each gated to `start + i*interval`.

    Uses time.monotonic() instead of cumulative sleeps so jitter doesn't
    drift across many iterations. Critical for SLO/latency tests that
    expect a stable TPS over a 50+ second streaming window.
    """
    for i in range(count):
        if interval > 0:
            target = start_monotonic + i * interval
            now = time.monotonic()
            if target > now:
                time.sleep(target - now)
        yield i


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        sys.stderr.write(f"[mock] {self.command} {self.path}\n")
        sys.stderr.flush()

    def _read_body(self) -> dict:
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length) if length else b"{}"
        try:
            return json.loads(raw)
        except Exception:
            return {}

    def _slow_callback_sink(self, status=200, response_body=b'{"ok":true}'):
        length = int(self.headers.get("Content-Length", "0"))
        if length:
            self.rfile.read(length)
        delay = float(os.environ.get("CALLBACK_DELAY", "0"))
        time.sleep(delay)
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(response_body)))
        self.end_headers()
        self.wfile.write(response_body)

    def do_POST(self):
        STATS.enter()
        try:
            self._dispatch_post()
        finally:
            STATS.exit()

    def _dispatch_post(self):
        if self.path.startswith("/api/public/ingestion") or self.path.startswith(
            "/api/v1/series"
        ):
            self._slow_callback_sink(
                status=207, response_body=b'{"successes":[],"errors":[]}'
            )
            STATS.request("callback", "sink", 207)
            return
        if self.path.startswith("/api/hooks/"):
            self._slow_callback_sink(status=200)
            STATS.request("callback", "sink", 200)
            return
        if self.path in ("/v1/messages", "/messages"):
            self._handle_anthropic()
            return
        # Gemini: /v1beta/models/<m>:generateContent  or :streamGenerateContent
        # Tolerates absence of `/v1beta` prefix too (some clients set api_base
        # to host root and pass `v1beta/models/...` themselves).
        if ":generateContent" in self.path or ":streamGenerateContent" in self.path:
            self._handle_gemini()
            return
        if self.path not in ("/v1/chat/completions", "/chat/completions"):
            self.send_response(404)
            self.end_headers()
            self.wfile.write(b'{"error":"not found"}')
            STATS.request("other", "unary", 404)
            return
        self._handle_openai()

    def _hdr(self, name: str) -> Optional[str]:
        """Return X-Mock-* header value if present. Case-insensitive."""
        # http.server lowercases header names internally — `.get()` is
        # case-insensitive only when the supplied name is exact-case of
        # what HTTP put in the message, so always go through .lower().
        for k, v in self.headers.items():
            if k.lower() == name.lower():
                return v
        return None

    def _int_override(
        self, header: str, body_key: str, body: dict, default: int
    ) -> int:
        """Header wins; body_key is legacy fallback; default last."""
        raw = self._hdr(header)
        if raw is not None:
            try:
                return int(raw)
            except ValueError:
                pass
        return int(body.get(body_key, default))

    def _should_fail(self, params: dict) -> Optional[int]:
        """Decide whether to inject a failure for this request.

        Order of precedence:
          1. `X-Mock-Fail: <code>` header — deterministic, exact-status.
          2. `FAIL_RATE` env — random per-request.
        Returns the HTTP status code to emit, or None for success.
        """
        forced = params.get("force_fail")
        if forced:
            try:
                return int(forced)
            except ValueError:
                pass
        try:
            rate = float(os.environ.get("FAIL_RATE", "0"))
        except ValueError:
            rate = 0.0
        if rate > 0 and random.random() < rate:
            return 503
        return None

    def _send_error(self, status: int, provider: str) -> None:
        """Emit a provider-shaped error body for `status`. Closes the response."""
        if provider == "openai":
            body = {
                "error": {
                    "message": f"mock {status} simulated",
                    "type": (
                        "server_error" if status >= 500 else "invalid_request_error"
                    ),
                    "code": str(status),
                }
            }
        elif provider == "anthropic":
            body = {
                "type": "error",
                "error": {
                    "type": {
                        503: "overloaded_error",
                        429: "rate_limit_error",
                        401: "authentication_error",
                        400: "invalid_request_error",
                        500: "api_error",
                    }.get(status, "api_error"),
                    "message": f"mock {status} simulated",
                },
            }
        else:  # gemini
            body = {
                "error": {
                    "code": status,
                    "message": f"mock {status} simulated",
                    "status": {
                        503: "UNAVAILABLE",
                        429: "RESOURCE_EXHAUSTED",
                        401: "UNAUTHENTICATED",
                        400: "INVALID_ARGUMENT",
                        500: "INTERNAL",
                    }.get(status, "INTERNAL"),
                }
            }
        bb = json.dumps(body).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(bb)))
        if status == 429:
            self.send_header("Retry-After", "1")
        self.end_headers()
        self.wfile.write(bb)
        STATS.request(provider, "unary", status)
        STATS.fail(status)

    @staticmethod
    def _validate_openai(body: dict) -> Optional[str]:
        """Return an error message if `body` is malformed for /v1/chat/completions.

        Catches: missing model, missing/empty messages, wrong types. Does NOT
        enforce role enum (OpenAI accepts arbitrary strings in practice).
        """
        if not isinstance(body.get("model"), str) or not body["model"]:
            return "missing or invalid 'model'"
        msgs = body.get("messages")
        if not isinstance(msgs, list) or len(msgs) == 0:
            return "missing or empty 'messages' list"
        for i, m in enumerate(msgs):
            if not isinstance(m, dict):
                return f"messages[{i}] must be an object"
            if "role" not in m:
                return f"messages[{i}] missing 'role'"
            if "content" not in m and "tool_calls" not in m and "tool_call_id" not in m:
                return f"messages[{i}] missing 'content'"
        return None

    @staticmethod
    def _validate_anthropic(body: dict) -> Optional[str]:
        """Return an error message if `body` is malformed for /v1/messages."""
        if not isinstance(body.get("model"), str) or not body["model"]:
            return "missing or invalid 'model'"
        msgs = body.get("messages")
        if not isinstance(msgs, list) or len(msgs) == 0:
            return "missing or empty 'messages' list"
        if "max_tokens" not in body:
            # Anthropic requires max_tokens; litellm injects a default so we
            # warn but don't reject — useful to surface litellm bugs that strip it.
            pass
        for i, m in enumerate(msgs):
            if not isinstance(m, dict):
                return f"messages[{i}] must be an object"
            if m.get("role") not in ("user", "assistant"):
                return f"messages[{i}].role must be 'user' or 'assistant'"
            if "content" not in m:
                return f"messages[{i}] missing 'content'"
        return None

    @staticmethod
    def _validate_gemini(body: dict) -> Optional[str]:
        """Return an error message if `body` is malformed for /v1beta/models/*:generateContent."""
        contents = body.get("contents")
        if not isinstance(contents, list) or len(contents) == 0:
            return "missing or empty 'contents' list"
        for i, c in enumerate(contents):
            if not isinstance(c, dict):
                return f"contents[{i}] must be an object"
            if not isinstance(c.get("parts"), list) or len(c["parts"]) == 0:
                return f"contents[{i}] missing or empty 'parts'"
        return None

    def _params(self, body: dict) -> dict:
        return {
            "ttft_ms": self._int_override(
                "X-Mock-TTFT-Ms", "mock_ttft_ms", body, DEFAULT_TTFT_MS
            ),
            "tps": self._int_override("X-Mock-TPS", "mock_tps", body, DEFAULT_TPS),
            "n_chunks": self._int_override(
                "X-Mock-Chunks", "mock_chunks", body, DEFAULT_CHUNKS
            ),
            "chunk_chars": self._int_override(
                "X-Mock-Chunk-Chars", "mock_chunk_chars", body, 40
            ),
            "full_chars": self._int_override(
                "X-Mock-Full-Chars", "mock_full_chars", body, 8000
            ),
            "is_stream": bool(body.get("stream")),
            "force_fail": self._hdr("X-Mock-Fail"),  # str like "503" or None
            "tool_call": self._parse_tool_call(self._hdr("X-Mock-Tool-Call")),
        }

    @staticmethod
    def _parse_tool_call(spec: Optional[str]) -> Optional[dict]:
        """Parse `name(k1=v1,k2=v2)` into {name, args}. Returns None if unset.

        Whitespace is tolerated. Argument values are kept as strings — the
        emitter wraps them in a JSON object that real provider SDKs decode.
        Examples:
          get_weather(city=Tokyo,unit=celsius)
          add(a=1,b=2)
          ping()
        """
        if not spec:
            return None
        spec = spec.strip()
        if "(" not in spec or not spec.endswith(")"):
            return {"name": spec, "args": {}}
        name, rest = spec.split("(", 1)
        rest = rest[:-1].strip()  # drop trailing ')'
        args: dict = {}
        if rest:
            for kv in rest.split(","):
                if "=" in kv:
                    k, v = kv.split("=", 1)
                    args[k.strip()] = v.strip()
        return {"name": name.strip(), "args": args}

    def _handle_openai(self):
        body = self._read_body()
        err = self._validate_openai(body)
        if err:
            err_body = json.dumps(
                {
                    "error": {
                        "message": f"mock validation: {err}",
                        "type": "invalid_request_error",
                        "code": "400",
                    }
                }
            ).encode()
            self.send_response(400)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(err_body)))
            self.end_headers()
            self.wfile.write(err_body)
            STATS.request("openai", "unary", 400)
            return

        p = self._params(body)
        model = body.get("model", "mock-model")
        prompt_tokens = self._count_prompt_chars_openai(body) // 4

        status = self._should_fail(p)
        if status:
            self._send_error(status, provider="openai")
            return

        if p["tool_call"]:
            self._openai_tool_call(model, prompt_tokens, p)
            STATS.request("openai", "stream" if p["is_stream"] else "unary", 200)
            return

        if p["is_stream"]:
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            try:
                if p["ttft_ms"]:
                    time.sleep(p["ttft_ms"] / 1000.0)
                interval = (1.0 / p["tps"]) if p["tps"] > 0 else 0
                start = time.monotonic()
                for i in paced_iter(start, interval, p["n_chunks"]):
                    self.wfile.write(
                        sse_chunk_openai(model, i, chunk_text(p["chunk_chars"]))
                    )
                    self.wfile.flush()
                self.wfile.write(
                    sse_chunk_openai(model, p["n_chunks"], "", finish=True)
                )
                self.wfile.write(b"data: [DONE]\n\n")
                self.wfile.flush()
                STATS.chunk("openai", p["n_chunks"])
                STATS.request("openai", "stream", 200)
            except (BrokenPipeError, ConnectionResetError):
                STATS.request("openai", "stream", 499)  # client closed
            return

        # non-stream
        completion_tokens = max(1, p["full_chars"] // 4)
        resp = {
            "id": "chatcmpl-mock-1",
            "object": "chat.completion",
            "created": int(time.time()),
            "model": model,
            "choices": [
                {
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": chunk_text(p["full_chars"]),
                    },
                    "finish_reason": "stop",
                }
            ],
            "usage": {
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": prompt_tokens + completion_tokens,
            },
        }
        bb = json.dumps(resp, ensure_ascii=False).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(bb)))
        self.end_headers()
        self.wfile.write(bb)
        STATS.request("openai", "unary", 200)

    def _openai_tool_call(self, model: str, prompt_tokens: int, p: dict) -> None:
        """Emit an OpenAI-shape tool_call response (stream or non-stream)."""
        tc = p["tool_call"]
        call_id = "call_mock_1"
        args_json = json.dumps(tc["args"])
        if p["is_stream"]:
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            try:
                if p["ttft_ms"]:
                    time.sleep(p["ttft_ms"] / 1000.0)
                base = {
                    "id": "chatcmpl-mock-tc",
                    "object": "chat.completion.chunk",
                    "created": int(time.time()),
                    "model": model,
                }
                # 1. role chunk
                self.wfile.write(
                    b"data: "
                    + compact_json(
                        {
                            **base,
                            "choices": [
                                {
                                    "index": 0,
                                    "delta": {"role": "assistant"},
                                    "finish_reason": None,
                                }
                            ],
                        }
                    )
                    + b"\n\n"
                )
                # 2. tool_call function name chunk
                self.wfile.write(
                    b"data: "
                    + compact_json(
                        {
                            **base,
                            "choices": [
                                {
                                    "index": 0,
                                    "delta": {
                                        "tool_calls": [
                                            {
                                                "index": 0,
                                                "id": call_id,
                                                "type": "function",
                                                "function": {
                                                    "name": tc["name"],
                                                    "arguments": "",
                                                },
                                            }
                                        ]
                                    },
                                    "finish_reason": None,
                                }
                            ],
                        }
                    )
                    + b"\n\n"
                )
                # 3. arguments chunks (1 char at a time to mimic real provider)
                for ch in args_json:
                    self.wfile.write(
                        b"data: "
                        + compact_json(
                            {
                                **base,
                                "choices": [
                                    {
                                        "index": 0,
                                        "delta": {
                                            "tool_calls": [
                                                {
                                                    "index": 0,
                                                    "function": {"arguments": ch},
                                                }
                                            ]
                                        },
                                        "finish_reason": None,
                                    }
                                ],
                            }
                        )
                        + b"\n\n"
                    )
                # 4. finish
                self.wfile.write(
                    b"data: "
                    + compact_json(
                        {
                            **base,
                            "choices": [
                                {
                                    "index": 0,
                                    "delta": {},
                                    "finish_reason": "tool_calls",
                                }
                            ],
                        }
                    )
                    + b"\n\n"
                )
                self.wfile.write(b"data: [DONE]\n\n")
                self.wfile.flush()
            except (BrokenPipeError, ConnectionResetError):
                pass
            return

        # Non-stream tool_call
        resp = {
            "id": "chatcmpl-mock-tc",
            "object": "chat.completion",
            "created": int(time.time()),
            "model": model,
            "choices": [
                {
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": None,
                        "tool_calls": [
                            {
                                "id": call_id,
                                "type": "function",
                                "function": {
                                    "name": tc["name"],
                                    "arguments": args_json,
                                },
                            }
                        ],
                    },
                    "finish_reason": "tool_calls",
                }
            ],
            "usage": {
                "prompt_tokens": prompt_tokens,
                "completion_tokens": len(args_json),
                "total_tokens": prompt_tokens + len(args_json),
            },
        }
        bb = json.dumps(resp).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(bb)))
        self.end_headers()
        self.wfile.write(bb)

    def _count_prompt_chars_openai(self, body):
        try:
            return sum(
                (
                    len(m.get("content", ""))
                    if isinstance(m.get("content"), str)
                    else sum(len(p.get("text", "")) for p in m.get("content", []))
                )
                for m in body.get("messages", [])
            )
        except Exception:
            return 0

    def _count_prompt_chars_anthropic(self, body):
        try:
            n = 0
            system = body.get("system", "")
            if isinstance(system, str):
                n += len(system)
            elif isinstance(system, list):
                n += sum(len(b.get("text", "")) for b in system if isinstance(b, dict))
            for m in body.get("messages", []):
                c = m.get("content", "")
                if isinstance(c, str):
                    n += len(c)
                elif isinstance(c, list):
                    n += sum(len(b.get("text", "")) for b in c if isinstance(b, dict))
            return n
        except Exception:
            return 0

    def _handle_anthropic(self):
        body = self._read_body()
        err = self._validate_anthropic(body)
        if err:
            err_body = json.dumps(
                {
                    "type": "error",
                    "error": {
                        "type": "invalid_request_error",
                        "message": f"mock validation: {err}",
                    },
                }
            ).encode()
            self.send_response(400)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(err_body)))
            self.end_headers()
            self.wfile.write(err_body)
            STATS.request("anthropic", "unary", 400)
            return

        p = self._params(body)
        model = body.get("model", "mock-claude")
        input_tokens = max(1, self._count_prompt_chars_anthropic(body) // 4)
        msg_id = f"msg_mock_{int(time.time() * 1000)}"

        status = self._should_fail(p)
        if status:
            self._send_error(status, provider="anthropic")
            return

        if p["tool_call"]:
            self._anthropic_tool_call(model, msg_id, input_tokens, p)
            STATS.request("anthropic", "stream" if p["is_stream"] else "unary", 200)
            return

        if p["is_stream"]:
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            try:
                # TTFT delay BEFORE message_start (matches real Anthropic behavior)
                if p["ttft_ms"]:
                    time.sleep(p["ttft_ms"] / 1000.0)
                self.wfile.write(
                    anthropic_event(
                        "message_start",
                        {
                            "type": "message_start",
                            "message": {
                                "id": msg_id,
                                "type": "message",
                                "role": "assistant",
                                "content": [],
                                "model": model,
                                "stop_reason": None,
                                "stop_sequence": None,
                                "usage": {
                                    "input_tokens": input_tokens,
                                    "output_tokens": 1,
                                },
                            },
                        },
                    )
                )
                self.wfile.write(
                    anthropic_event(
                        "content_block_start",
                        {
                            "type": "content_block_start",
                            "index": 0,
                            "content_block": {"type": "text", "text": ""},
                        },
                    )
                )
                interval = (1.0 / p["tps"]) if p["tps"] > 0 else 0
                start = time.monotonic()
                for _ in paced_iter(start, interval, p["n_chunks"]):
                    self.wfile.write(
                        anthropic_event(
                            "content_block_delta",
                            {
                                "type": "content_block_delta",
                                "index": 0,
                                "delta": {
                                    "type": "text_delta",
                                    "text": chunk_text(p["chunk_chars"]),
                                },
                            },
                        )
                    )
                    self.wfile.flush()
                self.wfile.write(
                    anthropic_event(
                        "content_block_stop",
                        {
                            "type": "content_block_stop",
                            "index": 0,
                        },
                    )
                )
                out_t = max(1, p["n_chunks"] * p["chunk_chars"] // 4)
                self.wfile.write(
                    anthropic_event(
                        "message_delta",
                        {
                            "type": "message_delta",
                            "delta": {"stop_reason": "end_turn", "stop_sequence": None},
                            "usage": {"output_tokens": out_t},
                        },
                    )
                )
                self.wfile.write(
                    anthropic_event("message_stop", {"type": "message_stop"})
                )
                self.wfile.flush()
                STATS.chunk("anthropic", p["n_chunks"])
                STATS.request("anthropic", "stream", 200)
            except (BrokenPipeError, ConnectionResetError):
                STATS.request("anthropic", "stream", 499)
            return

        out_t = max(1, p["full_chars"] // 4)
        resp = {
            "id": msg_id,
            "type": "message",
            "role": "assistant",
            "content": [{"type": "text", "text": chunk_text(p["full_chars"])}],
            "model": model,
            "stop_reason": "end_turn",
            "stop_sequence": None,
            "usage": {"input_tokens": input_tokens, "output_tokens": out_t},
        }
        bb = json.dumps(resp, ensure_ascii=False).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(bb)))
        self.end_headers()
        self.wfile.write(bb)
        STATS.request("anthropic", "unary", 200)

    def _anthropic_tool_call(
        self, model: str, msg_id: str, input_tokens: int, p: dict
    ) -> None:
        """Emit Anthropic-shape tool_use response (stream or non-stream)."""
        tc = p["tool_call"]
        args_json = json.dumps(tc["args"])
        tool_use_id = "toolu_mock_1"

        if p["is_stream"]:
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            try:
                if p["ttft_ms"]:
                    time.sleep(p["ttft_ms"] / 1000.0)
                self.wfile.write(
                    anthropic_event(
                        "message_start",
                        {
                            "type": "message_start",
                            "message": {
                                "id": msg_id,
                                "type": "message",
                                "role": "assistant",
                                "content": [],
                                "model": model,
                                "stop_reason": None,
                                "stop_sequence": None,
                                "usage": {
                                    "input_tokens": input_tokens,
                                    "output_tokens": 1,
                                },
                            },
                        },
                    )
                )
                # tool_use content block starts with empty input
                self.wfile.write(
                    anthropic_event(
                        "content_block_start",
                        {
                            "type": "content_block_start",
                            "index": 0,
                            "content_block": {
                                "type": "tool_use",
                                "id": tool_use_id,
                                "name": tc["name"],
                                "input": {},
                            },
                        },
                    )
                )
                # partial_json deltas streaming the args
                for ch in args_json:
                    self.wfile.write(
                        anthropic_event(
                            "content_block_delta",
                            {
                                "type": "content_block_delta",
                                "index": 0,
                                "delta": {
                                    "type": "input_json_delta",
                                    "partial_json": ch,
                                },
                            },
                        )
                    )
                self.wfile.write(
                    anthropic_event(
                        "content_block_stop",
                        {
                            "type": "content_block_stop",
                            "index": 0,
                        },
                    )
                )
                self.wfile.write(
                    anthropic_event(
                        "message_delta",
                        {
                            "type": "message_delta",
                            "delta": {"stop_reason": "tool_use", "stop_sequence": None},
                            "usage": {"output_tokens": len(args_json)},
                        },
                    )
                )
                self.wfile.write(
                    anthropic_event("message_stop", {"type": "message_stop"})
                )
                self.wfile.flush()
            except (BrokenPipeError, ConnectionResetError):
                pass
            return

        # Non-stream tool_use
        resp = {
            "id": msg_id,
            "type": "message",
            "role": "assistant",
            "content": [
                {
                    "type": "tool_use",
                    "id": tool_use_id,
                    "name": tc["name"],
                    "input": tc["args"],
                }
            ],
            "model": model,
            "stop_reason": "tool_use",
            "stop_sequence": None,
            "usage": {"input_tokens": input_tokens, "output_tokens": len(args_json)},
        }
        bb = json.dumps(resp).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(bb)))
        self.end_headers()
        self.wfile.write(bb)

    def _count_prompt_chars_gemini(self, body):
        """Gemini request shape: contents=[{role, parts:[{text|inline_data|file_data}]}], system_instruction:{parts:[...]}"""
        try:
            n = 0
            sysi = body.get("system_instruction") or body.get("systemInstruction") or {}
            for part in (sysi.get("parts") or []) if isinstance(sysi, dict) else []:
                if isinstance(part, dict):
                    n += len(part.get("text", "") or "")
            for c in body.get("contents", []):
                for part in c.get("parts", []) if isinstance(c, dict) else []:
                    if isinstance(part, dict):
                        n += len(part.get("text", "") or "")
                        # inline_data.data is base64 — count its length as bytes
                        idata = part.get("inline_data") or part.get("inlineData") or {}
                        n += len((idata or {}).get("data", "") or "")
            return n
        except Exception:
            return 0

    def _handle_gemini(self):
        body = self._read_body()
        err = self._validate_gemini(body)
        if err:
            err_body = json.dumps(
                {
                    "error": {
                        "code": 400,
                        "status": "INVALID_ARGUMENT",
                        "message": f"mock validation: {err}",
                    }
                }
            ).encode()
            self.send_response(400)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(err_body)))
            self.end_headers()
            self.wfile.write(err_body)
            STATS.request("gemini", "unary", 400)
            return

        p = self._params(body)
        # Action determined by URL, not body
        model, is_stream = parse_gemini_path(self.path)
        # Gemini doesn't carry `stream` in body — overwrite from URL so
        # tool-call emitter sees the correct value.
        p = {**p, "is_stream": is_stream}
        prompt_chars = self._count_prompt_chars_gemini(body)
        input_tokens = max(1, prompt_chars // 4)

        status = self._should_fail(p)
        if status:
            self._send_error(status, provider="gemini")
            return

        if p["tool_call"]:
            self._gemini_tool_call(model, input_tokens, p)
            STATS.request("gemini", "stream" if p["is_stream"] else "unary", 200)
            return

        if is_stream:
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            try:
                if p["ttft_ms"]:
                    time.sleep(p["ttft_ms"] / 1000.0)
                interval = (1.0 / p["tps"]) if p["tps"] > 0 else 0
                start = time.monotonic()
                for _ in paced_iter(start, interval, p["n_chunks"]):
                    self.wfile.write(gemini_chunk(chunk_text(p["chunk_chars"])))
                    self.wfile.flush()
                output_tokens = max(1, p["n_chunks"] * p["chunk_chars"] // 4)
                self.wfile.write(
                    gemini_chunk(
                        "",
                        finish=True,
                        prompt_tokens=input_tokens,
                        output_tokens=output_tokens,
                    )
                )
                self.wfile.flush()
                STATS.chunk("gemini", p["n_chunks"])
                STATS.request("gemini", "stream", 200)
            except (BrokenPipeError, ConnectionResetError):
                STATS.request("gemini", "stream", 499)
            return

        # non-stream generateContent
        out_t = max(1, p["full_chars"] // 4)
        resp = {
            "candidates": [
                {
                    "content": {
                        "parts": [{"text": chunk_text(p["full_chars"])}],
                        "role": "model",
                    },
                    "finishReason": "STOP",
                    "index": 0,
                }
            ],
            "usageMetadata": {
                "promptTokenCount": input_tokens,
                "candidatesTokenCount": out_t,
                "totalTokenCount": input_tokens + out_t,
            },
            "modelVersion": model,
        }
        bb = json.dumps(resp, ensure_ascii=False).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(bb)))
        self.end_headers()
        self.wfile.write(bb)
        STATS.request("gemini", "unary", 200)

    def _gemini_tool_call(self, model: str, input_tokens: int, p: dict) -> None:
        """Emit Gemini-shape functionCall (stream or non-stream).

        Gemini doesn't stream tool-call args delta-by-delta in the public
        SDK shape — the whole `functionCall` block lands in a single chunk
        marked as `parts: [{functionCall: {name, args}}]`. We mirror that.
        """
        tc = p["tool_call"]
        if p["is_stream"]:
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            try:
                if p["ttft_ms"]:
                    time.sleep(p["ttft_ms"] / 1000.0)
                # Chunk with the full functionCall + finish marker
                obj = {
                    "candidates": [
                        {
                            "content": {
                                "parts": [
                                    {
                                        "functionCall": {
                                            "name": tc["name"],
                                            "args": tc["args"],
                                        }
                                    }
                                ],
                                "role": "model",
                            },
                            "finishReason": "STOP",
                            "index": 0,
                        }
                    ],
                    "usageMetadata": {
                        "promptTokenCount": input_tokens,
                        "candidatesTokenCount": 1,
                        "totalTokenCount": input_tokens + 1,
                    },
                }
                self.wfile.write(b"data: " + compact_json(obj) + b"\r\n\r\n")
                self.wfile.flush()
            except (BrokenPipeError, ConnectionResetError):
                pass
            return

        # Non-stream functionCall
        resp = {
            "candidates": [
                {
                    "content": {
                        "parts": [
                            {
                                "functionCall": {
                                    "name": tc["name"],
                                    "args": tc["args"],
                                }
                            }
                        ],
                        "role": "model",
                    },
                    "finishReason": "STOP",
                    "index": 0,
                }
            ],
            "usageMetadata": {
                "promptTokenCount": input_tokens,
                "candidatesTokenCount": 1,
                "totalTokenCount": input_tokens + 1,
            },
            "modelVersion": model,
        }
        bb = json.dumps(resp).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(bb)))
        self.end_headers()
        self.wfile.write(bb)

    def do_GET(self):
        if self.path in ("/", "/healthz", "/v1/models"):
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(b'{"ok":true}')
            return
        if self.path.startswith("/api/public/projects"):
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(b'{"data":[{"id":"mock-project","name":"mock"}]}')
            return
        # Test introspection — snapshot of all counters (JSON).
        if self.path == "/__mock__/state":
            body = json.dumps(STATS.snapshot(), indent=2).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        # Test introspection — reset counters (POST or GET, both work for convenience).
        if self.path == "/__mock__/reset":
            with STATS._lock:
                STATS.requests.clear()
                STATS.chunks.clear()
                STATS.errors_injected.clear()
                STATS.in_flight = 0
                STATS.started_at = time.time()
            self.send_response(204)
            self.end_headers()
            return
        # Prometheus scrape endpoint.
        if self.path == "/metrics":
            body = self._render_prometheus().encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; version=0.0.4")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        self.send_response(404)
        self.end_headers()

    def _render_prometheus(self) -> str:
        """Render Stats as Prometheus text format. Stdlib-only, no prom client."""
        snap = STATS.snapshot()
        out = []
        out.append("# HELP mock_uptime_seconds Mock process uptime")
        out.append("# TYPE mock_uptime_seconds gauge")
        out.append(f"mock_uptime_seconds {snap['uptime_s']}")
        out.append("# HELP mock_in_flight_requests Current in-flight requests")
        out.append("# TYPE mock_in_flight_requests gauge")
        out.append(f"mock_in_flight_requests {snap['in_flight']}")
        out.append("# HELP mock_requests_total Requests by provider, mode, status")
        out.append("# TYPE mock_requests_total counter")
        for key, n in snap["requests"].items():
            try:
                provider, mode, status = key.split(":")
                out.append(
                    f'mock_requests_total{{provider="{provider}",mode="{mode}",status="{status}"}} {n}'
                )
            except ValueError:
                pass
        out.append("# HELP mock_chunks_total Streamed chunks by provider")
        out.append("# TYPE mock_chunks_total counter")
        for provider, n in snap["chunks"].items():
            out.append(f'mock_chunks_total{{provider="{provider}"}} {n}')
        out.append(
            "# HELP mock_errors_injected_total Forced/rate-injected failures by status"
        )
        out.append("# TYPE mock_errors_injected_total counter")
        for status, n in snap["errors_injected"].items():
            out.append(f'mock_errors_injected_total{{status="{status}"}} {n}')
        return "\n".join(out) + "\n"


def main() -> None:
    server = ThreadingHTTPServer(("0.0.0.0", PORT), Handler)
    print(
        f"mock listening on :{PORT} (TTFT={DEFAULT_TTFT_MS}ms TPS={DEFAULT_TPS} chunks={DEFAULT_CHUNKS})",
        flush=True,
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.shutdown()


if __name__ == "__main__":
    main()
